# Default values for elcep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maibornwolff/elcep
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

elasticsearch:
  host: "http://elasticsearch"
  port: 9200

files: 
  # Declare your queries as an array
  queries: 
    - all_exceptions=message:*exception
    - all_other_exceptions=log:*exception